// Package main generates command documentation from the centralized registry.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/bmf-san/ggc/v8/cmd/command"
)

const commandsReferencePath = "docs/guide/commands.md"

func main() {
	if err := writeCommandsReference(commandsReferencePath); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing commands reference: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("%s regenerated from registry\n", commandsReferencePath)
}

func writeCommandsReference(path string) error {
	registry := command.NewRegistry()
	commands := registry.VisibleCommands()
	sort.Slice(commands, func(i, j int) bool {
		if commands[i].Category != commands[j].Category {
			return command.CategoryOrder(commands[i].Category) < command.CategoryOrder(commands[j].Category)
		}
		return commands[i].Name < commands[j].Name
	})

	var b strings.Builder
	b.WriteString("# Commands\n\n")
	b.WriteString("This reference is auto-generated from the command registry in [`cmd/command/`](https://github.com/bmf-san/ggc/tree/main/cmd/command). Do not edit this file by hand; run `make docs`.\n\n")
	b.WriteString("For quick lookup, `ggc help` lists every command and `ggc help <command>` shows the same detail in your terminal.\n\n")
	b.WriteString("## Table of contents\n\n")

	byCategory := make(map[command.Category][]command.Info)
	for i := range commands {
		c := commands[i]
		byCategory[c.Category] = append(byCategory[c.Category], c)
	}
	for _, cat := range command.OrderedCategories() {
		list := byCategory[cat]
		if len(list) == 0 {
			continue
		}
		anchor := strings.ToLower(string(cat))
		fmt.Fprintf(&b, "- [%s](#%s)\n", cat, anchor)
	}
	b.WriteString("\n")

	for _, cat := range command.OrderedCategories() {
		list := byCategory[cat]
		if len(list) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", cat)
		for i := range list {
			writeCommandSection(&b, &list[i])
		}
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeCommandSection(b *strings.Builder, c *command.Info) {
	fmt.Fprintf(b, "### `ggc %s`\n\n", c.Name)
	if c.Summary != "" {
		fmt.Fprintf(b, "%s.\n\n", strings.TrimSuffix(c.Summary, "."))
	}
	writeAliases(b, c.Aliases)
	writeUsageBlock(b, "Usage", c.Usage)
	writeSubcommandsBlock(b, visibleSubs(c.Subcommands))
	writeUsageBlock(b, "Examples", c.Examples)
}

func writeAliases(b *strings.Builder, aliases []string) {
	if len(aliases) == 0 {
		return
	}
	quoted := make([]string, 0, len(aliases))
	for _, a := range aliases {
		quoted = append(quoted, "`"+a+"`")
	}
	fmt.Fprintf(b, "**Aliases:** %s\n\n", strings.Join(quoted, ", "))
}

func writeUsageBlock(b *strings.Builder, label string, lines []string) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "**%s:**\n\n```bash\n", label)
	for _, l := range lines {
		fmt.Fprintf(b, "%s\n", l)
	}
	b.WriteString("```\n\n")
}

func writeSubcommandsBlock(b *strings.Builder, subs []command.SubcommandInfo) {
	if len(subs) == 0 {
		return
	}
	b.WriteString("**Subcommands:**\n\n")
	b.WriteString("| Subcommand | Description |\n")
	b.WriteString("|---|---|\n")
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name < subs[j].Name })
	for i := range subs {
		fmt.Fprintf(b, "| `%s` | %s |\n", subs[i].Name, subs[i].Summary)
	}
	b.WriteString("\n")
	for i := range subs {
		s := &subs[i]
		if len(s.Examples) == 0 {
			continue
		}
		fmt.Fprintf(b, "_Examples for `%s`:_\n\n```bash\n", s.Name)
		for _, ex := range s.Examples {
			fmt.Fprintf(b, "%s\n", ex)
		}
		b.WriteString("```\n\n")
	}
}

func visibleSubs(subs []command.SubcommandInfo) []command.SubcommandInfo {
	var out []command.SubcommandInfo
	for _, s := range subs {
		if !s.Hidden {
			out = append(out, s)
		}
	}
	return out
}
